import csv

rows = [
    ["question", "answer", "intent"],
    ["How can I reset my password?", "Go to Settings > Security > Reset Password. You'll receive an email with instructions.", "password_reset"],
    ["I forgot my password", "Click on 'Forgot Password' on the login page and follow the email instructions.", "password_reset"],
    ["How do I change my password?", "Go to Account Settings > Change Password. Enter your current password and new password.", "password_reset"],
    ["Can I reset my password without email?", "No, password reset requires email verification for security reasons.", "password_reset"],
    ["What to do if password reset email doesn't arrive?", "Check spam folder and wait 5 minutes. Use resend option or contact support.", "password_reset"],
    ["How often should I change my password?", "We recommend changing your password every 90 days for security.", "password_reset"],
    ["Can I use special characters in password?", "Yes, special characters are allowed and recommended for stronger passwords.", "password_reset"],
    ["Password requirements?", "Minimum 8 characters with at least 1 number and 1 special character.", "password_reset"],
    ["How to delete my account?", "Contact customer support at support@company.com with your account details.", "account_delete"],
    ["I want to close my account", "Please email account deletion request to support@company.com. Processing takes 24 hours.", "account_delete"],
    ["How to permanently delete account?", "Account deletion is permanent. Email support@company.com to initiate the process.", "account_delete"],
    ["Can I recover deleted account?", "No, deleted accounts cannot be recovered within 30 days of deletion request.", "account_delete"],
    ["What happens to my data after deletion?", "All personal data is permanently erased within 30 days per GDPR compliance.", "account_delete"],
    ["Can I temporarily disable account?", "Yes, you can pause your account instead of deleting it.", "account_delete"],
    ["How to cancel account deletion?", "Email support immediately within 24 hours of deletion request.", "account_delete"],
    ["Will I get refund after deletion?", "Prorated refunds are processed within 14 business days after account deletion.", "account_delete"],
    ["What is your refund policy?", "Full refund within 7 days of purchase. Partial refund after 7 days.", "refund_policy"],
    ["How do I get a refund?", "Contact support with your order number and reason for refund.", "refund_policy"],
    ["Can I return a product?", "Yes, products can be returned within 30 days with original packaging.", "refund_policy"],
    ["How long do refunds take?", "Refunds are processed within 5-7 business days after approval.", "refund_policy"],
    ["Do you offer partial refunds?", "Yes, partial refunds available based on usage time and circumstances.", "refund_policy"],
    ["Can I refund after 30 days?", "Exceptions considered case-by-case. Contact support to discuss.", "refund_policy"],
    ["How to check refund status?", "Track refund status in Account > Billing > Refund History.", "refund_policy"],
    ["Refund for annual subscription?", "Yes, prorated refund for unused months of annual subscription.", "refund_policy"],
    ["How to contact support?", "Email support@company.com or chat with us 24/7.", "contact_support"],
    ["What are your support hours?", "Support is available 24 hours a day, 7 days a week.", "contact_support"],
    ["Is there phone support?", "Yes, call us at 1-800-123-4567 Monday-Friday 9 AM-6 PM EST.", "contact_support"],
    ["How to report a bug?", "Please email bug reports to bugs@company.com with screenshots.", "contact_support"],
    ["Live chat availability?", "Live chat available 24/7 on our website and mobile app.", "contact_support"],
    ["Support response time?", "Email responses within 4 hours. Chat immediate.", "contact_support"],
    ["Emergency support?", "For critical issues, use priority support or call emergency line.", "contact_support"],
    ["How to escalate an issue?", "Request supervisor in chat or email with URGENT in subject line.", "contact_support"],
    ["How much does premium cost?", "Premium plan is $9.99/month or $99.99/year (save 16%).", "pricing"],
    ["What payment methods do you accept?", "We accept Visa, Mastercard, American Express, and PayPal.", "pricing"],
    ["Is there a free trial?", "Yes, we offer a 14-day free trial on all premium plans.", "pricing"],
    ["Any student discounts?", "Yes, students get 50% off with valid .edu email verification.", "pricing"],
    ["Volume discounts available?", "Yes, team plans start at 5 users with 20% discount.", "pricing"],
    ["Do prices include tax?", "Prices shown exclude applicable taxes based on location.", "pricing"],
    ["Price match guarantee?", "We match competitor prices within 30 days of purchase.", "pricing"],
    ["Can I upgrade mid-cycle?", "Yes, upgrade anytime and pay prorated difference.", "pricing"],
    ["How to update billing information?", "Go to Settings > Billing to update payment methods.", "billing"],
    ["Why was I charged twice?", "Please check your bank statement. Contact support if duplicate charges persist.", "billing"],
    ["Can I change my billing cycle?", "Yes, switch from monthly to yearly in Account > Billing settings.", "billing"],
    ["How to download invoice?", "Invoices available in Account > Billing > Invoice History.", "billing"],
    ["Payment failed what now?", "Update payment method. System retries for 3 days before suspension.", "billing"],
    ["Can I use multiple payment methods?", "No, only one primary payment method can be active at a time.", "billing"],
    ["Is billing automatic?", "Yes, recurring billing is automatic. Cancel to stop future charges.", "billing"],
    ["How to change billing email?", "Update in Account > Settings > Email preferences.", "billing"],
    ["How do I cancel my subscription?", "Cancel anytime in Account > Subscription > Cancel.", "cancellation"],
    ["Can I pause my subscription?", "Yes, you can pause for 1-3 months in Account settings.", "cancellation"],
    ["Will I lose data after canceling?", "Your data is retained for 30 days after cancellation.", "cancellation"],
    ["How to reactivate cancelled account?", "Login and resubscribe within 30 days to restore your data.", "cancellation"],
    ["Cancellation confirmation?", "Email confirmation sent immediately. Check spam folder.", "cancellation"],
    ["Can I cancel anytime?", "Yes, no long-term contracts. Cancel whenever you want.", "cancellation"],
    ["What if I cancel mid-month?", "Access continues until end of current billing period.", "cancellation"],
    ["Cancellation fee?", "No cancellation fees for any plan.", "cancellation"],
    ["Is my data secure?", "Yes, we use 256-bit encryption and regular security audits.", "security"],
    ["How to enable two-factor authentication?", "Enable 2FA in Account > Security > Two-Factor Authentication.", "security"],
    ["Do you sell user data?", "No, we never sell user data. Privacy is our priority.", "security"],
    ["How to download my data?", "Request data export in Account > Privacy > Download Data.", "security"],
    ["Is my payment info safe?", "PCI compliant. Payment data never stored on our servers.", "security"],
    ["Security breach notification?", "Immediate notification within 24 hours of any breach detection.", "security"],
    ["Can I set IP restrictions?", "Enterprise plan includes IP whitelisting for extra security.", "security"],
    ["Session timeout settings?", "Auto-logout after 30 minutes inactivity. Adjustable in settings.", "security"],
    ["What features are included?", "Basic plan includes core features. Premium adds analytics and priority support.", "features"],
    ["How many users per account?", "Basic: 1 user, Premium: up to 5 users, Enterprise: unlimited.", "features"],
    ["Is there a mobile app?", "Yes, iOS and Android apps available on App Store and Google Play.", "features"],
    ["Can I integrate with other tools?", "Yes, we offer API access and Zapier integration on premium plans.", "features"],
    ["Offline mode available?", "Mobile apps support offline mode with auto-sync when online.", "features"],
    ["Custom branding options?", "Enterprise plan includes white-labeling and custom domain.", "features"],
    ["Analytics features?", "Premium includes advanced analytics and custom reports.", "features"],
    ["Export data formats?", "Export to CSV, Excel, PDF, and JSON formats available.", "features"],
    ["How to create account?", "Sign up with email or Google account on our homepage.", "account_management"],
    ["Can I change username?", "Username change available once every 30 days in settings.", "account_management"],
    ["How to update profile?", "Edit profile information in Account > Profile settings.", "account_management"],
    ["Multiple accounts allowed?", "One account per user. Contact sales for multi-account needs.", "account_management"],
    ["Email notifications setup?", "Manage notifications in Account > Settings > Notifications.", "notifications"],
    ["Can I customize alerts?", "Yes, custom alert rules available in premium plan.", "notifications"],
    ["Push notifications?", "Mobile app supports push notifications. Enable in device settings.", "notifications"],
    ["Notification frequency?", "Choose daily digest or real-time in notification preferences.", "notifications"],
    ["API rate limits?", "60 requests per minute for basic, 300 for premium API access.", "api"],
    ["API documentation?", "Developer docs at docs.company.com with code examples.", "api"],
    ["API key generation?", "Generate API keys in Developer Settings > API Access.", "api"],
    ["Webhook setup?", "Configure webhooks in Developer Settings > Webhooks.", "api"],
]

with open("data/faq.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerows(rows)

print("data/faq.csv fixed successfully!")